// Real Halo character meshes for the agent renderer. Data comes from
// game/characters-data.js (generated by scripts/convert-h3-assets.mjs from
// H3EK source art — Halo 2 marines/civilians/infection form, Halo 3 flood
// combat forms; see assets/NOTICE.txt). Each model is a small set of
// texture groups; the renderer draws one InstancedMesh per group.

import * as THREE from '../engine/vendor/three.webgpu.module.js';
import { CHARACTERS } from './characters-data.js';

const texLoader = new THREE.TextureLoader();
const texCache = {};
const partCache = new Map();
const texFor = (name) => {
  if (!texCache[name]) {
    const t = texLoader.load(`./assets/characters/${name}.png`);
    t.colorSpace = THREE.SRGBColorSpace;
    texCache[name] = t;
  }
  return texCache[name];
};

// [{ part, pivot, geometry, texture }] per model — geometry is meters, y-up,
// +X-forward, feet at y=0 (rotate with the same heading convention as the
// carry rifle). `part` is the rigid animation part (torso/head/armL/armR/
// legL/legR) and `pivot` its joint position in model space — the renderer
// swings each limb about its pivot for the procedural walk/attack cycles.
export const characterParts = (name) => {
  if (partCache.has(name)) return partCache.get(name);
  const model = CHARACTERS[name];
  const parts = model.groups.map((g) => {
    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.Float32BufferAttribute(g.pos, 3));
    geo.setAttribute('normal', new THREE.Float32BufferAttribute(g.norm, 3));
    geo.setAttribute('uv', new THREE.Float32BufferAttribute(g.uv, 2));
    geo.setIndex(g.idx);
    return { part: g.part, pivot: model.pivots[g.part] ?? null, geometry: geo, texture: texFor(g.tex) };
  });
  partCache.set(name, parts);
  return parts;
};
